name: booking_box
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  flutter_svg: ^2.0.4
  lottie: ^2.3.1
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.17.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.10.0
  flutter_spinkit: ^5.1.0
  simple_animations: ^4.2.0
  cached_network_image: ^3.3.0
  # firebase_core: ^3.13.0
  firebase_core_platform_interface: ^4.8.0
  firebase_analytics: ^10.4.4
  animated_floating_buttons: ^0.0.2
  firebase_messaging: ^14.6.5
  file_picker: ^10.1.9  
  awesome_dialog: ^3.0.2
  connectivity_plus: ^6.0.3
  # gallery_saver: ^2.3.2
  dio: ^5.5.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  # image_gallery_saver: ^2.0.3
  google_maps_flutter: ^2.7.0
  palette_generator: ^0.3.3+3
  google_sign_in: ^6.2.1
  firebase_auth: ^4.9.0
  photo_view: ^0.14.0
  equatable: ^2.0.5
  open_file: ^3.3.2
  json_annotation: any
  rive: 0.13.2
  saver_gallery: ^4.0.1
  google_fonts: ^4.0.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/images/social/
    - assets/images/logo/
    - assets/animation/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
