// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMU86zsJtMeEUPrLCO-Nku73fBTIoM4m0',
    appId: '1:456212219069:web:3230a442468ec9399123d4',
    messagingSenderId: '456212219069',
    projectId: 'viserlab-global-app-eaedd',
    authDomain: 'viserlab-global-app-eaedd.firebaseapp.com',
    storageBucket: 'viserlab-global-app-eaedd.appspot.com',
    measurementId: 'G-5JE2KRFH8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoCBGDYPzL-BWDNImb82rk3eqFCZGTNg',
    appId: '1:456212219069:android:5c33b952b25342159123d4',
    messagingSenderId: '456212219069',
    projectId: 'viserlab-global-app-eaedd',
    storageBucket: 'viserlab-global-app-eaedd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ubMrPEveb2oM-k7UOBdB-5jt85Hw0eI',
    appId: '1:456212219069:ios:9f722a3cd98c85489123d4',
    messagingSenderId: '456212219069',
    projectId: 'viserlab-global-app-eaedd',
    storageBucket: 'viserlab-global-app-eaedd.appspot.com',
    androidClientId: '456212219069-13hgcj5e10b4j96am0usl5hm7fa2jcfa.apps.googleusercontent.com',
    iosClientId: '456212219069-gr7mv12am5lv0lpruoi33u2gej4i59vv.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.bookingbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ubMrPEveb2oM-k7UOBdB-5jt85Hw0eI',
    appId: '1:456212219069:ios:9d344b11ece9710c9123d4',
    messagingSenderId: '456212219069',
    projectId: 'viserlab-global-app-eaedd',
    storageBucket: 'viserlab-global-app-eaedd.appspot.com',
    androidClientId: '456212219069-13hgcj5e10b4j96am0usl5hm7fa2jcfa.apps.googleusercontent.com',
    iosClientId: '456212219069-j5k1gi1818r7efbjqqj293vtuc17eai6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMU86zsJtMeEUPrLCO-Nku73fBTIoM4m0',
    appId: '1:456212219069:web:436b3bfbad4644b59123d4',
    messagingSenderId: '456212219069',
    projectId: 'viserlab-global-app-eaedd',
    authDomain: 'viserlab-global-app-eaedd.firebaseapp.com',
    storageBucket: 'viserlab-global-app-eaedd.appspot.com',
    measurementId: 'G-S5ZR7E20KL',
  );

}